apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s
spec:
  hosts:
    - role: controller+worker
      ssh:
        address: 127.0.0.1
      localhost:
        enabled: true
      noTaints: true
      installFlags: &installFlags
        - --disable-components konnectivity-server
  k0s:
    version: v1.26.0+k0s.0
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: ClusterConfig
      metadata:
        name: k0s
      spec:
        network:
          provider: calico
        api:
          extraArgs:
            service-node-port-range: "80-60000"
        extensions:
          helm:
            repositories: []
            charts: []